### PR TITLE
Fix login by face

### PR DESCRIPTION
**Pull request by danieltcacenco**

### CODE REVIEW

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Did not check if the login by FaceID is fixed. A textual mistake that we all-ready fixed is back. (again)
@danieltcacenco I would like you to ask you to add a screenshot of the welcoming screen where the AANMAKEN is changed to AANMELDEN. This textual mistake comes back everytime we checkout branches.

IMG_8FEDB58FEDA5-1

**Comment by danieltcacenco** [comment]
> Did not check if the login by FaceID is fixed. A textual mistake that we all-ready fixed is back. (again)
> @danieltcacenco I would like you to ask you to add a screenshot of the welcoming screen where the AANMAKEN is changed to AANMELDEN. This textual mistake comes back everytime we checkout branches.
> 
> IMG_8FEDB58FEDA5-1

done

**Review by GerbenBosschieter — APPROVED** [review]
Well still there are still typo's in this PR, I will just merge it and make a branch myself for the texts

**Comment by GerbenBosschieter** [comment]
@danieltcacenco this branch has some merge conflicts. I don't know if I should go on whats on develop to accept or this branch. I can see it also has some references to Pods , so don't want to change something that can break it. Could solve the conflicts or tell me what branch is leading in this case?

@jknnr fyi

**Comment by danieltcacenco** [comment]
done

**Comment by danieltcacenco** [comment]
> @danieltcacenco this branch has some merge conflicts. I don't know if I should go on whats on develop to accept or this branch. I can see it also has some references to Pods , so don't want to change something that can break it. Could solve the conflicts or tell me what branch is leading in this case?
> 
> @jknnr fyi

done

**Pull request merged**
