### PR TITLE
Feature/signupflow.fix

### PR DESCRIPTION
**Pull request by maxvisser**

### CODE REVIEW

**Comment by maxvisser** [comment]
@danieltcacenco I tried creating an new identity but i got a error saying my session expired after using the activate link.

session expired

**Comment by danieltcacenco** [comment]
done

**Comment by maxvisser** [comment]
tested it and my issue is fixed

**Comment by maxvisser** [comment]
image

1. title is not aligned with text
2. exit button is inverted compared to figma 
image
3. spacing between bar is not aligned

**Comment by maxvisser** [comment]
image

1. should be "Uw email" without capitals
2. the whole height of this input field seems to be abit off. How it should look:
image
edit: 2. also the bar is not as black as it should be (still grey)

**Comment by maxvisser** [comment]
image
1. too much padding between welkom bij Me and input field
2. Should be "Uw e-mail" instead of Email
3. too much padding between button and input field
4. and 6. some weird blue drop shadow
5. Should be "Apparaat" instead of apparat

**Pull request merged**
