### PR TITLE
Release/v0.4.3

### PR DESCRIPTION
**Pull request by GerbenBosschieter**

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-09 at 00 16 21

- Text area where transaction details are displayed need more space
- Textual change -> Totaal prijs should be Totale prijs
- Only show price and not the word "optional" or the parentheses around the price

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-09 at 00 25 51

- Add dutch translation. Discount = Korting
- If it's a discount with percentages pleas show it like this: 20% instead of 20,00%.
- In this scenario the sponsor does a subsidy of €5,-. Pleas show the amount that the sponsor will pay (just like the first screenshot in this PR). BUT only show the amount if the sponsor does pay an amount. There wil be scenario's where the don't do a subsidy

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-09 at 00 30 41

- Keyboard doesn't behave properly. Return doesn't hide the keybooard. Pleas fix this

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-09 at 00 32 24

- Text area of transaction details needs more height. Content of the text area should be vertically aligned.
- Pleas display € 5,00 as €5,- just like how you display the prices in the transaction details
- Text area for leaving  note is a is behind the button. Can't scroll or something to focus more on the Note area

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-09 at 00 32 24

- All whole euro prices (so without any number after the coma) should be displayed the same. So pleas display this price here as €5,- instead of €5,00

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-09 at 00 39 18

- Dark mode has text that you can;t read. Pleas change background color to the greyish color you use at other places where you use dark mode. For example the image below:
- If you change the background color, the titles should also change color so you can read them

Screenshot 2021-01-09 at 00 42 59

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-09 at 00 45 46

- If it's a discount with % pleas display the number as 20% instead of 20.00%

**Comment by GerbenBosschieter** [comment]
The app doesn't display the actions below when scanning voucher. These actions are "Free" or "Free with a subsidy from the sponsor. So currenlty doens't support these scenario's

Screenshot 2021-01-09 at 00 46 56

**Comment by GerbenBosschieter** [comment]
Please add some changes If the action has a normal price but the sponsor did a subsidy of 100% of the price .

Screenshot 2021-01-09 at 00 59 33

- Remove € sign if the price is Free and it shows Gratis. 

Payment confirmation should change in this scenario. It display € 0.00 pleas change it like the second image below.

1. € 0.00
Screenshot 2021-01-09 at 00 52 46

2. Gratis
Screenshot 2021-01-09 at 00 54 07

**Comment by GerbenBosschieter** [comment]
> The app doesn't display the actions below when scanning voucher. These actions are "Free" or "Free with a subsidy from the sponsor. So currenlty doens't support these scenario's
> 
> Screenshot 2021-01-09 at 00 46 56

This is not fixed yet

**Comment by GerbenBosschieter** [comment]
> Screenshot 2021-01-09 at 00 32 24
> 
> * All whole euro prices (so without any number after the coma) should be displayed the same. So pleas display this price here as €5,- instead of €5,00

By fixing the above a new small problem in introduced. You can scroll down to see the call to action to do the payment but I don't think it's clear enough. Would be nice if we could display the CTA or show something to indicate that hey can scroll or maybe move the text a bit so you have more space for the call to action?

Screenshot 2021-01-10 at 12 27 19

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-10 at 12 33 10

This one is a nice to have and I didn't mention it before. But it would be nice to not display the sentence if the price is Free (Gratis).

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-10 at 12 45 28 1

**Scenario:** Completely free with subsidy sponsor
- Must have: no information about the amount the sponsor will pay is visible. Transaction details area is cut off.
- Could have: move up the "Gratis" section a bit. (this should influence the payment screen when there is a sentence and a amount displayee)

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-10 at 12 49 42
Screenshot 2021-01-10 at 12 50 12

- should have: If there is no number after the comma, pleas display €5,- instead € 5,00 
- should have: same counts for when there is discount in €. Pleas display €20,- instead of €20.00

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-10 at 12 53 49

- Transaction overview provider: If the amountr is. € 0,- don't show it

**Comment by GerbenBosschieter** [comment]
- Transaction details: Format should be € value. So € 0.00 instead of 0.00 €
- Transaction details: If the price is € 0.- display Gratis (without the euro symbol)

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-10 at 13 00 52

- If the scenario is a discount, pleas display Korting instead of Totale prijs

**Comment by GerbenBosschieter** [comment]
- Should have: If i scan the Stadjerspas it will only display a maximum of 10 actions while there are 16. This problem is a combination of the platform itself. But also the iOS does something wrong. The app only displays 10. While Android displays 13.

@danieltcacenco could you check of the iOS app has a limit of 10 and change it to unlimited xD?

**Review by jamalv — APPROVED** [review]
# 💯

**Review by danieltcacenco — APPROVED** [review]

**Review by maxvisser — APPROVED** [review]

**Comment by jamalv** [comment]
currently waiting for review by apple

**Pull request merged**
