### PR TITLE
teamforus/me#434 done

### PR DESCRIPTION
**Pull request by danieltcacenco**

### CODE REVIEW

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
I can see the commit that should fix this.
If I build it and set the BaseUrl to production and log in on my own profile I can see see all the options with the voucher and the voucher itself.

**Comment by GerbenBosschieter** [comment]
Eey guys, Tried it again. But conclussion is the same. Could you heck this out?
@danieltcacenco

**Comment by danieltcacenco** [comment]
> Eey guys, Tried it again. But conclussion is the same. Could you heck this out?
> @danieltcacenco

Hey, could you upload some screen please, to now sure what is about.

**Comment by GerbenBosschieter** [comment]
@danieltcacenco Below you can find screenshots of my own personal account with expired vouchers and still have the option to open them and qr-codes are not hide.

Could you maybe maker screenshots of the fix itself if it's done? If you need an account with expired vouchers, tell me :)

IMG_0609
IMG_0610

**Comment by GerbenBosschieter** [comment]
Closed this PR. issue itself is already fixed with this PR: https://github.com/teamforus/me-ios/pull/62

**Pull request closed without merging**
