### PR TITLE
Release v0.0.5

### PR DESCRIPTION
**Pull request by maxvisser**
changelog:
added products voucher
fixed crash with payment
improve ui
confirm email
Translations

### CODE REVIEW

**Comment by jamalv** [comment]
created pr with correct info: https://github.com/teamforus/me-ios/pull/44

**Comment by maxvisser** [comment]
ah you understand it wrong, Both apps can have their own versioning but I will just tag it with the backend version as when you want to download a me app thats tested with v0.0.7 of the backend.

**Comment by jamalv** [comment]
yea, this is confusing, we'll need to set up some standards for this :) 

So to clarify the release number in the App Store for this release will be 0.0.5?

**Comment by maxvisser** [comment]
yes thats ok

**Pull request merged**
