### PR TITLE
Release v0.0.4

### PR DESCRIPTION
**Pull request by maxvisser**
changelog:
- Fix crash with payment
- Product voucher
- add confirm email for create new profiel
- dutch translations

### CODE REVIEW

**Comment by maxvisser** [comment]
I think is a great new release for iOS, it will be used to make screenshots for the app store for now and already for adding providers.

**Comment by maxvisser** [comment]
Can you guys approve these. Of course you will notice more issues, add them as backlog items.

**Comment by maxvisser** [comment]
I added the fix for build environments to this release.

**Comment by jamalv** [comment]
Crashes on product vouchers

**Pull request closed without merging**
