### PR TITLE
Add git ignore file in me app i os and clean from pods

### PR DESCRIPTION
**Pull request by danieltcacenco**

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
I like this one xD Makes it easier building

**Comment by jknnr** [comment]
> I like this one xD Makes it easier building

then approve :-P

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
This branch can't open the files for me-ios. Like the project itself is ignored now

**Comment by danieltcacenco** [comment]
You mean error what is shown from github, or you try? Because right now you shoud make pod install before open right file.

**Comment by GerbenBosschieter** [comment]
worked

**Review by GerbenBosschieter — APPROVED** [review]

**Pull request merged**
