### PR TITLE
Release/v0.3.1

### PR DESCRIPTION
**Pull request by maxvisser**
Changelog:
New routes (identity email)
Add price back to product reservation
Localization issues (missing translations)
Euro symbol on product reservation list
Removal of flashlight option
Placeholder names on test transaction (Removal of DenyK; RIP)
Design improvements for records

### CODE REVIEW

**Comment by GerbenBosschieter** [comment]
Is this release on test flight?

**Comment by maxvisser** [comment]
Are you able to build it yourself?  I prefer that over testflight

**Comment by GerbenBosschieter** [comment]
@maxvisser no, and you know

**Comment by maxvisser** [comment]
@danieltcacenco @jknnr could you put the release branch in testflight?

**Comment by maxvisser** [comment]
IMG_F9CCD5E4C6B6-1
DanyK is gone but we still have here 'NOT 2 DAGEN VALID' and 'Label'

I propose to change 'NOT 2 DAGEN VALID' to 'Test organisatie' and remove Label

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
Still some minor issues with this build:
- Icon to archive is visible but no feature behind it. (nothing happends if you press on it)
- No price or euro sign added to product voucher (see image1)
- Weird markdown added to a logout confirmation message (see image2)
- NOT 2 DAGEN GELDIG VALID sentence is still there. (see image3)

**Image 1**
IMG_0FC920C4038F-1

**Image 2**
IMG_0363

**Image 3**

**Review by GerbenBosschieter — CHANGES_REQUESTED** [review]
- No e-mail send if you want to log in. This happens on staging and production environment. On dev it does work.
- Test transaction has a random price. There was no request to add this, see image: 
IMG_0368

**Review by GerbenBosschieter — APPROVED** [review]

**Pull request merged**
