### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by maxvisser**
rewrote the app from the ground up with a different method

### CODE REVIEW

**Review by GerbenBosschieter — COMMENTED** [review]
I will not approve yet. 
Some of these features are only available on the beta app cant install this on my phone.
- Have to resend invitation to my apple ID to get acces, but apple connect giving me a hard time.
- Can't build it from Xcode because of, well yea Apple. iOS version is to high for my Xcode version and if I want to update XCode I need to update my complete OS. 

Will try again tomorrow

**Review by GerbenBosschieter — DISMISSED** [review]
@danieltcacenco before we can release this I want you to look at these issues, some of them have comments for more information.


- [ Show expiration date on voucher details #281 ](https://github.com/teamforus/me/issues/281)
- [ add message when backend is in maintenance mode #220](https://github.com/teamforus/me/issues/220)
- [ Can't create New Me - Profile #302](https://github.com/teamforus/me/issues/302)
- [ Loading animation is stuck in a loop after scanning Login QR-code #301](https://github.com/teamforus/me/issues/301)
- [ Kies organisatie is double #294 (this one not really a reason to block the release, but still would be nice to fix this)](https://github.com/teamforus/me/issues/294)

This one I did not test yet:
- [ Organisation context switch while doing a payment #193](https://github.com/teamforus/me/issues/193)

**Comment by danieltcacenco** [comment]
New build on alpha is ready for new test.

**Comment by maxvisser** [comment]
@danieltcacenco I found some issues with localisation and some textual mistakes that need to be changed:
- [Close needs to be translated](https://github.com/teamforus/me/issues/306)
- [Textual change: Dit is uw voucher in de vorm van een QR-code](https://github.com/teamforus/me/issues/308)
- [Localisation: Yes/No when scan to login](https://github.com/teamforus/me/issues/309)
- [Localisation: Error Labels creating identity](https://github.com/teamforus/me/issues/310)
- [Localisation: Given Name on creating identity](https://github.com/teamforus/me/issues/311)
- [Localisation: header Verify you account ](https://github.com/teamforus/me/issues/312)
- [Textual change: subtitle of bevestig code ](https://github.com/teamforus/me/issues/313)
- [Localisation: Success! ](https://github.com/teamforus/me/issues/314)
- [Textual change: 'Mail provider from product voucher'-popup ](https://github.com/teamforus/me/issues/315)

Small issue with design, when no name for user:
- [When no Given Name and Family Name center e-mailadres](https://github.com/teamforus/me/issues/316)

Some issues I see with the blue avatar opening records page, I would remove it and change the UX to better fit design:
- [Remove blue avatar to open up records on voucher page.](https://github.com/teamforus/me/issues/307)
- [Make whole profile clickable to open up records page](https://github.com/teamforus/me/issues/317)

**Pull request merged**
